CREATE TABLE DEPARTMENT(
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL
);

CREATE TABLE EMPLOYEE(
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	SALARY INTEGER,
	BIRTHDAY DATE,
	ID_DEPARTMENT INTEGER,
	FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT(ID)
);

INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, "HUMAN RESOURCES");
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, "IT");
INSERT INTO DEPARTMENT (ID, NAME) VALUES (3, "SALES");
INSERT INTO DEPARTMENT (ID, NAME) VALUES (4, "PRODUCTION");
INSERT INTO DEPARTMENT (ID, NAME) VALUES (5, "MARKETING");
INSERT INTO DEPARTMENT (ID, NAME) VALUES (6, "ACCOUONTIND AND FINANCE");
INSERT INTO DEPARTMENT (ID, NAME) VALUES (7, "PURCHASING");

INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (1, "MATEO",                     20000, "1990-09-12", 1);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (2, "JUAN",                      20000, "1991-12-13", 1);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (3, "MARCOS",                    20000, "1992-01-14", 2);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (4, "LUISA",                     20000, "1993-02-15", 2);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (5, "ELENA",                     20000, "1994-03-16", 3);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (6, "ROSALVA",                   20000, "1995-04-17", 3);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (7, "ABRAHAM",                   20000, "1995-05-18", 4);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (8, "ELIOT",                     20000, "1996-06-18", 4);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (9, "TIMOTEO",                   20000, "1996-07-19", 5);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (10, "PETRONILO",                20000, "1991-08-20", 5);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (11, "PROFESOR JAMES MORIARTI",  20000, "1992-10-21", 6);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (12, "BRUCE WANE",               20000, "1992-11-22", 6);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (13, "SHREK",                    20000, "1993-05-23", 7);
INSERT INTO EMPLOYEE (ID, NAME, SALARY, BIRTHDAY, ID_DEPARTMET) VALUES (14, "JUANA LA CUBANA",          20000, "1994-02-24", 7);